### ISSUE TITLE
visible thread and arrow color with dark theme

### ISSUE THREAD

**Issue by pierrre** [g3rv4/Refined#33] opened 2019-04-19 07:07 UTC
### Involved feature
visible thread

### Steps to reproduce
enable visible thread and install https://chrome.google.com/webstore/detail/dark-theme-for-slack/begdfkhhegoognioipgofimponkeiiah

### Expected behavior
It would be nice to have an option to change the arrow color.

### Actual behavior
The arrow is invisible (black on black).

**Comment by g3rv4** [comment] 2019-04-19 16:30
heh, yeah... you’re right, and hovering on a message doesn’t highlight other messages in the conversation. I’ll work on it (unless you want to take a stab at it)

**Comment by pierrre** [comment] 2019-04-21 12:02
Hello !
Sorry I'm not a web developer, so I can't really help you on this issue. 😞

**Comment by g3rv4** [comment] 2019-04-21 15:17
no problem :) I’m going to work on it, since it’s the only reason why I disabled dark reader on slack (and I’m happy to read I’m not the only one using it).

I have a 3 months old at home, so I can’t make any promises as to when (just that it will get fixed)

**Comment by g3rv4** [comment] 2019-05-05 13:39
Fixed in v.2.2.8. That version is available on Chrome now (and it will be on Firefox as soon as they fix their [certificate shenanigans](https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047)).

I've also sent a PR to darkreader https://github.com/darkreader/darkreader/pull/1294 to fix the hover colors. While they don't merge it, you can apply that style so that the hover color works right with it.

**Closed as completed by g3rv4** 2019-05-05 13:39 UTC
Labels: bug, good first issue

**Comment by g3rv4** [comment] 2019-05-05 13:50
Oh, sorry... I just see that you use "Dark theme for Slack" and not "Dark Reader". Even the author from "Dark theme for Slack" [recommends Dark Reader on the project's readme](https://github.com/Bigsy/dark-slack-theme).

That's where I've sent the PR to fix the broadcast thingy and you can manually tweak before they accept the PR. This is how it looks:

![visibleOnDark](https://gervas.io/visibleThreadsDark.gif)

**Comment by pierrre** [comment] 2019-05-05 14:12
thank you ! 👍

**Comment by g3rv4** [comment] 2019-05-05 18:43
If you enjoy the extension, a review on the store would be highly appreciated :)

**Comment by g3rv4** [comment] 2019-05-06 12:19
I've just shipped 2.2.10, with a fix that's going to make it look nicer for both "Dark theme for Slack" and not "Dark Reader" (without any custom rules).

Thanks again for bringing this up. I'm really happy to be able to use dark mode in Slack again.

**Comment by pierrre** [comment] 2019-05-06 12:24
Is the "hover color" ?
Very nice ! :+1:

**Comment by g3rv4** [comment] 2019-05-06 12:24
yes! the hover color... it was impossible to tell which message a reply was intended to reply before
